

export const englishNames: { [key: string]: string } = {
    a: "Andrew",
    b: "Brenda",
    c: "Christopher",
    d: "Diana",
    e: "Edward",
    f: "Fiona",
    g: "George",
    h: "Hannah",
    i: "Ian",
    j: "Julia",
    k: "Kevin",
    l: "Laura",
    m: "Matthew",
    n: "Natalie",
    o: "Oliver",
    p: "Pamela",
    q: "Quentin",
    r: "Rachel",
    s: "Steven",
    t: "Theresa",
    u: "Ursula",
    v: "Victor",
    w: "Wendy",
    x: "Xavier",
    y: "Yvonne",
    z: "Zachary",
    A: "Alice",
    B: "Brian",
    C: "Catherine",
    D: "Daniel",
    E: "Emily",
    F: "Frank",
    G: "Grace",
    H: "Harry",
    I: "Isabella",
    J: "James",
    K: "Katherine",
    L: "Liam",
    M: "Megan",
    N: "Noah",
    O: "Olivia",
    P: "Patrick",
    Q: "Quinn",
    R: "Robert",
    S: "Sophia",
    T: "Thomas",
    U: "Una",
    V: "Victoria",
    W: "William",
    X: "Xander",
    Y: "Yara",
    Z: "Zane"
};

export const emailAddresses: { [key: string]: string } = {
    a: "andrew@example.com",
    b: "brenda@example.com",
    c: "christopher@example.com",
    d: "diana@example.com",
    e: "edward@example.com",
    f: "fiona@example.com",
    g: "george@example.com",
    h: "hannah@example.com",
    i: "ian@example.com",
    j: "julia@example.com",
    k: "kevin@example.com",
    l: "laura@example.com",
    m: "matthew@example.com",
    n: "natalie@example.com",
    o: "oliver@example.com",
    p: "pamela@example.com",
    q: "quentin@example.com",
    r: "rachel@example.com",
    s: "steven@example.com",
    t: "theresa@example.com",
    u: "ursula@example.com",
    v: "victor@example.com",
    w: "wendy@example.com",
    x: "xavier@example.com",
    y: "yvonne@example.com",
    z: "zachary@example.com",
    A: "alice@example.com",
    B: "brian@example.com",
    C: "catherine@example.com",
    D: "daniel@example.com",
    E: "emily@example.com",
    F: "frank@example.com",
    G: "grace@example.com",
    H: "harry@example.com",
    I: "isabella@example.com",
    J: "james@example.com",
    K: "katherine@example.com",
    L: "liam@example.com",
    M: "megan@example.com",
    N: "noah@example.com",
    O: "olivia@example.com",
    P: "patrick@example.com",
    Q: "quinn@example.com",
    R: "robert@example.com",
    S: "sophia@example.com",
    T: "thomas@example.com",
    U: "una@example.com",
    V: "victoria@example.com",
    W: "william@example.com",
    X: "xander@example.com",
    Y: "yara@example.com",
    Z: "zane@example.com"
};

export const alarmNames: { [key: string]: string } = {
    a: "Morning Workout Alarm",
    b: "Breakfast Reminder",
    c: "Conference Call Alarm",
    d: "Daily Standup Meeting Alarm",
    e: "Evening Walk Reminder",
    f: "Family Time Alarm",
    g: "Grocery Shopping Reminder",
    h: "Homework Time Alarm",
    i: "Important Task Reminder",
    j: "Jogging Time Alarm",
    k: "Kids' Bedtime Alarm",
    l: "Lunch Break Alarm",
    m: "Morning Meditation Alarm",
    n: "Nap Time Alarm",
    o: "Office Meeting Reminder",
    p: "Project Deadline Alarm",
    q: "Quiet Time Reminder",
    r: "Reading Time Alarm",
    s: "Study Session Alarm",
    t: "Tea Break Reminder",
    u: "Urgent Meeting Alarm",
    v: "Vacation Planning Reminder",
    w: "Workout Session Alarm",
    x: "Xylophone Practice Alarm",
    y: "Yoga Class Reminder",
    z: "Zen Time Alarm"
};

export const calendarEvents: { [key: string]: string } = {
    a: "Annual General Meeting",
    b: "Board of Directors Meeting",
    c: "Conference Call with Clients",
    d: "Department Strategy Session",
    e: "Executive Leadership Summit",
    f: "Finance Committee Review",
    g: "Global Marketing Webinar",
    h: "HR Policy Update Training",
    i: "IT Infrastructure Upgrade",
    j: "Joint Venture Planning Meeting",
    k: "Keynote Speaker Event",
    l: "Legal Compliance Workshop",
    m: "My Birthday!",
    n: "Networking Lunch",
    o: "Operations Team Sync",
    p: "Product Launch Event",
    q: "Quarterly Business Review",
    r: "Risk Management Seminar",
    s: "Stakeholder Engagement Session",
    t: "Team Building Activity",
    u: "User Experience Focus Group",
    v: "Vendor Contract Negotiation",
    w: "Weekly Staff Meeting",
    x: "eXecutive Roundtable Discussion",
    y: "Year-End Financial Audit",
    z: "Zoom Conference with Partners"
};

export const calendarEventDescriptions: { [key: string]: string } = {
    a: "Discussion on company performance and future strategies for the next fiscal year.",
    b: "Meeting to review and approve major decisions and policies.",
    c: "Update call with clients to discuss ongoing projects and future opportunities.",
    d: "Session to outline department goals and strategies for the coming quarter.",
    e: "Summit to discuss leadership strategies and company direction.",
    f: "Review of financial reports and budget allocations for the next quarter.",
    g: "Webinar to discuss global marketing trends and strategies.",
    h: "Training session on the latest updates to HR policies and procedures.",
    i: "Meeting to discuss and plan the upgrade of IT infrastructure.",
    j: "Planning meeting for upcoming joint ventures and collaborations.",
    k: "Event featuring a keynote speaker on industry trends and innovations.",
    l: "Workshop to ensure compliance with legal standards and regulations.",
    m: "Review of monthly sales performance and discussion of targets.",
    n: "Lunch event to network with industry professionals and stakeholders.",
    o: "Synchronization meeting for the operations team to align on tasks.",
    p: "Event to launch and demonstrate new products to the market.",
    q: "Review of business performance over the quarter and planning for the next.",
    r: "Seminar on identifying and managing business risks effectively.",
    s: "Session to engage with stakeholders and gather their input.",
    t: "Activity designed to improve team cohesion and collaboration.",
    u: "Focus group to gather feedback on user experience and product usability.",
    v: "Negotiation meeting to finalize vendor contracts and agreements.",
    w: "Regular staff meeting to discuss weekly updates and tasks.",
    x: "Roundtable discussion with executives on key business issues.",
    y: "Audit of financial statements and processes at the end of the year.",
    z: "Online conference with partners to discuss collaboration opportunities."
};

export const noteTitles: { [key: string]: string } = {
    a: "A Day in the Life",
    b: "Beautiful Memories",
    c: "Chasing Dreams",
    d: "Daily Reflections",
    e: "Endless Possibilities",
    f: "Finding Joy",
    g: "Grateful Moments",
    h: "Heartfelt Thoughts",
    i: "Inspiring Journeys",
    j: "Just Breathe",
    k: "Keeping Positive",
    l: "Life Lessons",
    m: "Mindful Moments",
    n: "New Beginnings",
    o: "Open Horizons",
    p: "Personal Growth",
    q: "Quiet Contemplations",
    r: "Radiant Days",
    s: "Serenity Now",
    t: "Thoughtful Insights",
    u: "Unwritten Pages",
    v: "Valuable Experiences",
    w: "Whispers of Wisdom",
    x: "Xtraordinary Adventures",
    y: "Yearning for More",
    z: "Zen Reflections",
    A: "A Glimpse of Serenity",
    B: "Bold New Ventures",
    C: "Creative Insights",
    D: "Daring to Dream",
    E: "Empowering Thoughts",
    F: "Forever Learning",
    G: "Guiding Stars",
    H: "Hopeful Horizons",
    I: "Innovative Ideas",
    J: "Journey of Growth",
    K: "Kindred Spirits",
    L: "Living Fully",
    M: "Moments of Magic",
    N: "Nurturing Ideas",
    O: "Outstanding Achievements",
    P: "Pursuing Excellence",
    Q: "Quest for Knowledge",
    R: "Remarkable Journeys",
    S: "Soothing Reflections",
    T: "Timeless Wisdom",
    U: "Unwavering Faith",
    V: "Vibrant Visions",
    W: "Wonderful Experiences",
    X: "eXploring Potential",
    Y: "Yearlong Journey",
    Z: "Zealous Endeavors"
};

export const noteSentences: { [key: string]: string } = {
    a: "Always remember to stay positive and approach each day with a hopeful mindset.",
    b: "Be kind to yourself and others, as kindness can make a significant difference in someone's day.",
    c: "Consistency is the key to success; small, steady steps lead to big achievements.",
    d: "Don't forget to take breaks and allow yourself time to relax and recharge.",
    e: "Every day is a new opportunity to learn, grow, and improve yourself.",
    f: "Focus on the things that matter most to you and invest your energy in them.",
    g: "Gratitude turns what we have into enough and brings peace to our hearts.",
    h: "Hard work pays off in the long run, even if it doesn't seem like it at the moment.",
    i: "Invest in your personal growth and never stop seeking ways to better yourself.",
    j: "Just keep pushing forward, even when the journey seems tough and the path unclear.",
    k: "Keep a journal to track your progress, thoughts, and reflections.",
    l: "Learn something new every day to keep your mind sharp and open to new ideas.",
    m: "Make time for the things you love and the people who matter most to you.",
    n: "Never stop dreaming, as your dreams are the seeds of your future achievements.",
    o: "Opportunities are everywhere; you just need to be open and ready to seize them.",
    p: "Patience is a virtue that helps you endure and overcome challenges.",
    q: "Quiet moments bring clarity and allow you to reflect on your life's journey.",
    r: "Rest is essential for productivity, so ensure you get enough sleep and relaxation.",
    s: "Stay humble and stay hungry; always strive to learn and grow.",
    t: "Take time to reflect on your achievements and be proud of how far you've come.",
    u: "Use your time wisely, as it is one of your most valuable resources.",
    v: "Value the journey, not just the destination, and enjoy each step along the way.",
    w: "Work hard, stay humble, and never forget where you started.",
    x: "eXcel in what you do by giving it your best effort and maintaining high standards.",
    y: "You are capable of amazing things; believe in yourself and your abilities.",
    z: "Zero in on your goals and stay focused on achieving them.",
    A: "Always aim high and set ambitious goals for yourself.",
    B: "Believe in the power of your dreams and take steps towards making them a reality.",
    C: "Challenge yourself to grow beyond your comfort zone and embrace new experiences.",
    D: "Dedicate time to your passions and the activities that bring you joy.",
    E: "Embrace every moment, as life is made up of small, precious instances.",
    F: "Focus on the good in every situation, even when it's hard to find.",
    G: "Give your best effort in everything you do, and you will reap the rewards.",
    H: "Happiness is a choice; decide to be happy and find joy in the little things.",
    I: "Imagine the possibilities that lie ahead and work towards turning them into reality.",
    J: "Just do it, and do it well; don't let fear or doubt hold you back.",
    K: "Knowledge is power; keep learning and expanding your understanding of the world.",
    L: "Live each day to the fullest and make the most of every opportunity that comes your way.",
    M: "Make meaningful connections with others and cherish the relationships you have.",
    N: "Nurture your mind, body, and soul with positive habits and self-care.",
    O: "Open your heart to new experiences and embrace the unknown.",
    P: "Practice gratitude daily to cultivate a positive mindset and appreciate life's blessings.",
    Q: "Question the status quo and seek innovative solutions to problems.",
    R: "Remember that failure is a part of the journey to success; learn from your mistakes.",
    S: "Stay true to yourself and your values, even when faced with challenges.",
    T: "Take risks and step out of your comfort zone to achieve greatness.",
    U: "Understand that growth often comes from adversity and difficult experiences.",
    V: "Value your time and use it to pursue your passions and achieve your goals.",
    W: "Wisdom comes from experience; embrace life's lessons and grow from them.",
    X: "eXpect the best from yourself and strive for excellence in all that you do.",
    Y: "You are stronger than you think; believe in your resilience and capabilities.",
    Z: "Zeal and passion are the driving forces behind success; let them guide you."
};

export const anotherNoteSentences: { [key: string]: string } = {
    1: "A calm mind is a powerful tool.",
    2: "Believe in the magic of new beginnings.",
    3: "Courage is found in unlikely places.",
    4: "Dreams are the seeds of change.",
    5: "Embrace the journey, not just the destination.",
    6: "Faith can move mountains.",
    7: "Gratitude turns what we have into enough.",
    8: "Hope is the heartbeat of the soul.",
    9: "Imagination is the true magic carpet.",
    0: "Just keep going, no matter what.",
    '-': "Knowledge is power.",
    '/': "Love is the bridge between you and everything.",
    ':': "Moments of stillness are moments of clarity.",
    ';': "Never stop learning.",
    '(': "Opportunities are everywhere.",
    ')': "Patience is the companion of wisdom.",
    '¥': "Quality time is the best gift.",
    '&': "Resilience is built through overcoming challenges.",
    '@': "Success is a journey, not a destination.",
    '&quot;': "Trust the process.",
    '.': "Understanding leads to harmony.",
    ',': "Victory comes from finding your own path.",
    '?': "Wisdom begins in wonder.",
    '!': "eXperience is the teacher of all things.",
    '\'': "You are your best investment."
};

export const journalTitles: { [key: string]: string } = {
    a: "A New Adventure",
    b: "Beautiful Beginnings",
    c: "Creating Memories",
    d: "Dreams and Goals",
    e: "Everyday Miracles",
    f: "Finding Peace",
    g: "Grateful Heart",
    h: "Hope and Inspiration",
    i: "Inner Thoughts",
    j: "Joyful Moments",
    k: "Kaleidoscope of Thoughts",
    l: "Life's Journey",
    m: "Mindful Living",
    n: "New Horizons",
    o: "Open Heart",
    p: "Positive Reflections",
    q: "Quiet Moments",
    r: "Radiant Thoughts",
    s: "Soulful Reflections",
    t: "Timeless Memories",
    u: "Unique Experiences",
    v: "Vibrant Life",
    w: "Wandering Thoughts",
    x: "Xtraordinary Days",
    y: "Year of Growth",
    z: "Zen Moments",
    A: "A Journey of Growth",
    B: "Brilliant Ideas",
    C: "Captivating Experiences",
    D: "Dream Big",
    E: "Eternal Optimism",
    F: "Fascinating Stories",
    G: "Golden Memories",
    H: "Heartfelt Gratitude",
    I: "Inspirational Thoughts",
    J: "Joyful Reflections",
    K: "Kindred Spirits",
    L: "Life's Wonders",
    M: "Moments of Bliss",
    N: "New Discoveries",
    O: "Open Possibilities",
    P: "Purposeful Living",
    Q: "Quiet Reflections",
    R: "Radiant Journeys",
    S: "Serene Days",
    T: "Thoughtful Insights",
    U: "Uplifting Thoughts",
    V: "Vivid Impressions",
    W: "Wonderful Times",
    X: "eXploring Life",
    Y: "Yearning for Adventure",
    Z: "Zealous Pursuits"
};

export const journalSentences: { [key: string]: string } = {
    a: "A positive mindset fuels positive outcomes.",
    b: "Be the change you wish to see in the world.",
    c: "Cherish the moments that take your breath away.",
    d: "Do more of what makes you happy.",
    e: "Embrace the beauty of simplicity.",
    f: "Follow your heart and intuition.",
    g: "Gratitude is the key to a happy life.",
    h: "Happiness is a journey, not a destination.",
    i: "Inhale confidence, exhale doubt.",
    j: "Joy is found in the present moment.",
    k: "Keep pushing forward, no matter what.",
    l: "Live life to the fullest.",
    m: "Make today amazing.",
    n: "Never give up on your dreams.",
    o: "Opportunities don't happen, you create them.",
    p: "Practice makes perfect.",
    q: "Quiet the mind and the soul will speak.",
    r: "Rise above the storm and you will find the sunshine.",
    s: "Stay focused and never give up.",
    t: "Take it one day at a time.",
    u: "Unlock your potential by challenging yourself.",
    v: "Value every moment.",
    w: "Wake up with determination, go to bed with satisfaction.",
    x: "eXpect the best and prepare for it.",
    y: "You are capable of amazing things.",
    z: "Zen begins with the mind.",
    A: "Always believe in yourself.",
    B: "Be yourself; everyone else is already taken.",
    C: "Create your own sunshine.",
    D: "Dream big, work hard, stay focused.",
    E: "Every moment is a fresh beginning.",
    F: "Forget the mistakes, remember the lessons.",
    G: "Go the extra mile, it's never crowded.",
    H: "Happiness is not by chance, but by choice.",
    I: "It's not about having time, it's about making time.",
    J: "Just do it.",
    K: "Keep going; everything you need will come to you at the perfect time.",
    L: "Let your dreams be your wings.",
    M: "Make your life a masterpiece.",
    N: "Nothing is impossible.",
    O: "One step at a time.",
    P: "Positive thinking will let you do everything better.",
    Q: "Quitters never win, and winners never quit.",
    R: "Remember why you started.",
    S: "Success is not the key to happiness. Happiness is the key to success.",
    T: "The best way to predict the future is to create it.",
    U: "Understand that the journey is as important as the destination.",
    V: "Visualize your success.",
    W: "When you feel like quitting, think about why you started.",
    X: "eXcellence is not an act, but a habit.",
    Y: "Your only limit is your mind.",
    Z: "Zeal without knowledge is fire without light."
};

export const anotherJournalSentences: { [key: string]: string } = {
    1: "A calm mind is a powerful tool.",
    2: "Believe in the magic of new beginnings.",
    3: "Courage is found in unlikely places.",
    4: "Dreams are the seeds of change.",
    5: "Embrace the journey, not just the destination.",
    6: "Faith can move mountains.",
    7: "Gratitude turns what we have into enough.",
    8: "Hope is the heartbeat of the soul.",
    9: "Imagination is the true magic carpet.",
    0: "Just keep going, no matter what.",
    '-': "Knowledge is power.",
    '/': "Love is the bridge between you and everything.",
    ':': "Moments of stillness are moments of clarity.",
    ';': "Never stop learning.",
    '(': "Opportunities are everywhere.",
    ')': "Patience is the companion of wisdom.",
    '¥': "Quality time is the best gift.",
    '&': "Resilience is built through overcoming challenges.",
    '@': "Success is a journey, not a destination.",
    '&quot;': "Trust the process.",
    '.': "Understanding leads to harmony.",
    ',': "Victory comes from finding your own path.",
    '?': "Wisdom begins in wonder?",
    '!': "eXperience is the teacher of all things!",
    '\'': "You are your best investment.",
};
