

export const englishNames: { [key: string]: string } = {
    a: "Andrew",
    b: "Brenda",
    c: "Christopher",
    d: "Diana",
    e: "Edward",
    f: "Fiona",
    g: "George",
    h: "Hannah",
    i: "Ian",
    j: "Julia",
    k: "Kevin",
    l: "Laura",
    m: "Matthew",
    n: "Natalie",
    o: "Oliver",
    p: "Pamela",
    q: "Quentin",
    r: "Rachel",
    s: "Steven",
    t: "Theresa",
    u: "Ursula",
    v: "Victor",
    w: "Wendy",
    x: "Xavier",
    y: "Yvonne",
    z: "Zachary",
    A: "Alice",
    B: "Brian",
    C: "Catherine",
    D: "Daniel",
    E: "Emily",
    F: "Frank",
    G: "Grace",
    H: "Harry",
    I: "Isabella",
    J: "James",
    K: "Katherine",
    L: "Liam",
    M: "Megan",
    N: "Noah",
    O: "Olivia",
    P: "Patrick",
    Q: "Quinn",
    R: "Robert",
    S: "Sophia",
    T: "Thomas",
    U: "Una",
    V: "Victoria",
    W: "William",
    X: "Xander",
    Y: "Yara",
    Z: "Zane"
};

export const emailAddresses: { [key: string]: string } = {
    a: "andrew@example.com",
    b: "brenda@example.com",
    c: "christopher@example.com",
    d: "diana@example.com",
    e: "edward@example.com",
    f: "fiona@example.com",
    g: "george@example.com",
    h: "hannah@example.com",
    i: "ian@example.com",
    j: "julia@example.com",
    k: "kevin@example.com",
    l: "laura@example.com",
    m: "matthew@example.com",
    n: "natalie@example.com",
    o: "oliver@example.com",
    p: "pamela@example.com",
    q: "quentin@example.com",
    r: "rachel@example.com",
    s: "steven@example.com",
    t: "theresa@example.com",
    u: "ursula@example.com",
    v: "victor@example.com",
    w: "wendy@example.com",
    x: "xavier@example.com",
    y: "yvonne@example.com",
    z: "zachary@example.com",
    A: "alice@example.com",
    B: "brian@example.com",
    C: "catherine@example.com",
    D: "daniel@example.com",
    E: "emily@example.com",
    F: "frank@example.com",
    G: "grace@example.com",
    H: "harry@example.com",
    I: "isabella@example.com",
    J: "james@example.com",
    K: "katherine@example.com",
    L: "liam@example.com",
    M: "megan@example.com",
    N: "noah@example.com",
    O: "olivia@example.com",
    P: "patrick@example.com",
    Q: "quinn@example.com",
    R: "robert@example.com",
    S: "sophia@example.com",
    T: "thomas@example.com",
    U: "una@example.com",
    V: "victoria@example.com",
    W: "william@example.com",
    X: "xander@example.com",
    Y: "yara@example.com",
    Z: "zane@example.com"
};

export const alarmNames: { [key: string]: string } = {
    a: "Morning Workout Alarm",
    b: "Breakfast Reminder",
    c: "Conference Call Alarm",
    d: "Daily Standup Meeting Alarm",
    e: "Evening Walk Reminder",
    f: "Family Time Alarm",
    g: "Grocery Shopping Reminder",
    h: "Homework Time Alarm",
    i: "Important Task Reminder",
    j: "Jogging Time Alarm",
    k: "Kids' Bedtime Alarm",
    l: "Lunch Break Alarm",
    m: "Morning Meditation Alarm",
    n: "Nap Time Alarm",
    o: "Office Meeting Reminder",
    p: "Project Deadline Alarm",
    q: "Quiet Time Reminder",
    r: "Reading Time Alarm",
    s: "Study Session Alarm",
    t: "Tea Break Reminder",
    u: "Urgent Meeting Alarm",
    v: "Vacation Planning Reminder",
    w: "Workout Session Alarm",
    x: "Xylophone Practice Alarm",
    y: "Yoga Class Reminder",
    z: "Zen Time Alarm"
};

export const calendarEvents: { [key: string]: string } = {
    a: "Annual General Meeting",
    b: "Board of Directors Meeting",
    c: "Conference Call with Clients",
    d: "Department Strategy Session",
    e: "Executive Leadership Summit",
    f: "Finance Committee Review",
    g: "Global Marketing Webinar",
    h: "HR Policy Update Training",
    i: "IT Infrastructure Upgrade",
    j: "Joint Venture Planning Meeting",
    k: "Keynote Speaker Event",
    l: "Legal Compliance Workshop",
    m: "My Birthday!",
    n: "Networking Lunch",
    o: "Operations Team Sync",
    p: "Product Launch Event",
    q: "Quarterly Business Review",
    r: "Risk Management Seminar",
    s: "Stakeholder Engagement Session",
    t: "Team Building Activity",
    u: "User Experience Focus Group",
    v: "Vendor Contract Negotiation",
    w: "Weekly Staff Meeting",
    x: "eXecutive Roundtable Discussion",
    y: "Year-End Financial Audit",
    z: "Zoom Conference with Partners"
};

export const calendarEventDescriptions: { [key: string]: string } = {
    a: "Discussion on company performance and future strategies for the next fiscal year.",
    b: "Meeting to review and approve major decisions and policies.",
    c: "Update call with clients to discuss ongoing projects and future opportunities.",
    d: "Session to outline department goals and strategies for the coming quarter.",
    e: "Summit to discuss leadership strategies and company direction.",
    f: "Review of financial reports and budget allocations for the next quarter.",
    g: "Webinar to discuss global marketing trends and strategies.",
    h: "Training session on the latest updates to HR policies and procedures.",
    i: "Meeting to discuss and plan the upgrade of IT infrastructure.",
    j: "Planning meeting for upcoming joint ventures and collaborations.",
    k: "Event featuring a keynote speaker on industry trends and innovations.",
    l: "Workshop to ensure compliance with legal standards and regulations.",
    m: "Review of monthly sales performance and discussion of targets.",
    n: "Lunch event to network with industry professionals and stakeholders.",
    o: "Synchronization meeting for the operations team to align on tasks.",
    p: "Event to launch and demonstrate new products to the market.",
    q: "Review of business performance over the quarter and planning for the next.",
    r: "Seminar on identifying and managing business risks effectively.",
    s: "Session to engage with stakeholders and gather their input.",
    t: "Activity designed to improve team cohesion and collaboration.",
    u: "Focus group to gather feedback on user experience and product usability.",
    v: "Negotiation meeting to finalize vendor contracts and agreements.",
    w: "Regular staff meeting to discuss weekly updates and tasks.",
    x: "Roundtable discussion with executives on key business issues.",
    y: "Audit of financial statements and processes at the end of the year.",
    z: "Online conference with partners to discuss collaboration opportunities."
};
